//go:build !js && !wasm

package main

// placeholder_derivatives.go
// §10.6/§10.7 — DERIVED (LIGHT) RENDITIONS OF THE PLACEHOLDER PACK, GENERATED BY THE SERVER.
//
// WHY THIS EXISTS. The shipped pack is 117 PNGs totalling ~314 MB (avg 2.7 MB, 14 frames above
// 4 MB, one at 8.3 MB). Every one of those files is a fine ORIGINAL, and a terrible thing to
// fetch to paint a background: the boot slideshow alone would pull multi-megabyte art through
// the network before a player sees anything. The honest fix is a real derivative made by the
// authority that owns the art — not a client-side downscale (which would still have to download
// the 2.7 MB first, so it would fix nothing) and not a hand-made "small" file (which would be
// art nobody generated).
//
// WHAT MAKES IT HONEST:
//   - The DERIVATION IS INTEGER-ONLY. A deterministic box filter averages the covered source
//     pixels with uint64 accumulation, alpha-weighted (premultiplied) so a transparent frame
//     does not get dark halos. Same input bytes + same width ⇒ same output bytes, on any
//     machine, with no sampling jitter and no float anywhere.
//   - The DECLARED FACTS ARE MEASURED. Bytes come from the file that was just written, pixel
//     size from the image that was just encoded, and hash_hex is the sha256 of the actual
//     derived bytes — so a client that fetches the art can re-hash it and compare.
//   - THE SOURCE IS NAMED. Every derivative carries the source SKU, the source's real sha256,
//     its byte size and its pixel size, so "this is a derived rendition of frame X" is a
//     statement the payload can prove rather than imply.
//   - A REFUSAL IS REPORTED. A frame whose bytes cannot be decoded is recorded as failed WITH
//     THE REASON and is never replaced by invented art; the client keeps the original.
//   - THE ORIGINAL IS NEVER TOUCHED. Derivatives are written to their own root under
//     Public/Assets/Generated/… , so the pack the media policy validates is exactly the pack on
//     disk, and the catalogue's "the file list IS the SKU list" rule still holds.
//
// The pass is IDEMPOTENT and driven by a manifest: a record is reused while its recorded source
// hash matches the source file's real hash, so a restart does no work and a changed frame is
// re-derived instead of serving stale art. Generation NEVER blocks boot: it runs in the
// background with the six slideshow frames first, and every reader falls back to the original
// while a frame is still pending (reported as such).

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"image"
	"image/png"
	"io"
	"log"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"
)

const (
	// The two tiers the app actually paints. `slide` is the app boot / main menu and World
	// Dashboard background; `thumb` is a UI-tree / panel background where the art sits behind
	// content at low opacity.
	PlaceholderDerivativeSlideTier = "slide"
	PlaceholderDerivativeThumbTier = "thumb"

	// PlaceholderDerivativeSlideWidth is the widest a slide derivative may be. 512 px is ample
	// for a full-screen background painted at low opacity behind the app chrome.
	PlaceholderDerivativeSlideWidth uint64 = 512
	// PlaceholderDerivativeThumbWidth is the widest a thumb derivative may be.
	PlaceholderDerivativeThumbWidth uint64 = 128

	// placeholderDerivativeRoot is where derivatives are written, relative to the process
	// working directory. It lives UNDER the served tree on purpose: the static handler already
	// serves Public/, so a generated frame needs no new route and no invented URL.
	placeholderDerivativeRoot = "Public/Assets/Generated/NPC-helpers"

	// placeholderDerivativeURIPrefix is the same-origin form a derived frame is addressed by.
	// It is a path under /Assets/, which is the one scheme-less form the §10.3 media policy
	// accepts — so a derived rendition is a legal media URI, not a special case.
	placeholderDerivativeURIPrefix = "/Assets/Generated/NPC-helpers/"

	// placeholderDerivativeManifestFile is the self-describing index kept beside the art, so a
	// copied Generated/ folder carries its own provenance and a restart reuses it.
	placeholderDerivativeManifestFile = "derivatives.json"

	// placeholderDerivativeManifestVersion lets a future change to the filter or the tier set
	// invalidate the whole manifest instead of silently mixing two generations of art.
	placeholderDerivativeManifestVersion = 1
)

// PlaceholderDerivative is one derived rendition of one pack frame.
type PlaceholderDerivative struct {
	Tier string `json:"tier"`
	URI  string `json:"uri"`
	// Bytes / Width / Height / HashHex / MimeType are MEASURED from the derived file.
	Bytes    uint64 `json:"bytes"`
	Width    uint64 `json:"width"`
	Height   uint64 `json:"height"`
	HashHex  string `json:"hash_hex"`
	MimeType string `json:"mime_type"`
	// Passthrough marks a tier that needed no new file (the source is already at or below the
	// tier width). The derivative is then the source itself, and it says so.
	Passthrough bool      `json:"passthrough,omitempty"`
	GeneratedAt time.Time `json:"generated_at"`
}

// PlaceholderDerivativeRecord is the manifest entry for one SKU: the source it was derived from
// and the renditions that exist. `Failed` is the reason a derivation was refused — kept so a
// frame is not retried on every read, and so the refusal is visible rather than silent.
type PlaceholderDerivativeRecord struct {
	SKU           string                 `json:"sku"`
	SourceURI     string                 `json:"source_uri"`
	SourceHashHex string                 `json:"source_hash_hex"`
	SourceBytes   uint64                 `json:"source_bytes"`
	SourceWidth   uint64                 `json:"source_width"`
	SourceHeight  uint64                 `json:"source_height"`
	Slide         *PlaceholderDerivative `json:"slide,omitempty"`
	Thumb         *PlaceholderDerivative `json:"thumb,omitempty"`
	Failed        string                 `json:"failed,omitempty"`
	UpdatedAt     time.Time              `json:"updated_at"`
}

// PlaceholderDerivativeManifest is the on-disk index of every derived frame.
type PlaceholderDerivativeManifest struct {
	Version     int                                     `json:"version"`
	Root        string                                  `json:"root"`
	SlideWidth  uint64                                  `json:"slide_width"`
	ThumbWidth  uint64                                  `json:"thumb_width"`
	GeneratedAt time.Time                               `json:"generated_at"`
	Records     map[string]*PlaceholderDerivativeRecord `json:"records"`
}

// PlaceholderDerivativeStatus is the SERVED progress report - a CENSUS of the resting state, not a
// per-pass summary. A client can always tell whether the light art exists yet, and how much of the
// pack is still original, so "still heavy" is never a mystery:
//
//	derived + pending + failed == total
//
// There is deliberately NO `reused` field here. Reuse is a fact about ONE PASS (the pass result and
// the log line report it), and a resting-state read cannot know it - a field that always answered 0
// said "nothing was reused" after a restart that in fact rewrote nothing, which is exactly the kind
// of quiet falsehood this file exists to avoid.
type PlaceholderDerivativeStatus struct {
	Ready      bool `json:"ready"`
	InProgress bool `json:"in_progress"`
	Total      int  `json:"total"`
	// Derived counts frames whose slide AND thumb renditions are both present and recorded.
	Derived int `json:"derived"`
	// Pending counts frames with no usable record yet (still deriving, or half-written).
	Pending int `json:"pending"`
	// Failed counts frames the pass refused, each naming its reason in the catalogue.
	Failed      int       `json:"failed"`
	SlideWidth  uint64    `json:"slide_width"`
	ThumbWidth  uint64    `json:"thumb_width"`
	Root        string    `json:"root"`
	GeneratedAt time.Time `json:"generated_at"`
	Rule        string    `json:"rule"`
}

var (
	// placeholderDerivManifestMu guards the in-memory manifests + pass status. It is held only for
	// short map/field updates, never across a decode, so a reader never waits on the pass.
	//
	// The index is keyed by GENERATED ROOT so a test (or a second pack) can run a pass without
	// disturbing the shipped pack's index — the same discipline as the target struct.
	placeholderDerivManifestMu sync.Mutex
	placeholderDerivManifests  = make(map[string]*PlaceholderDerivativeManifest)
	placeholderDerivPassOn     bool
	placeholderDerivLastRun    time.Time

	// placeholderDerivPassMu serialises whole passes (and single-frame derivations), so two
	// callers can never encode the same frame into the same path at once.
	placeholderDerivPassMu sync.Mutex

	placeholderDerivWarmOnce sync.Once
)

// ── Manifest (provenance + idempotency) ──────────────────────────────────────────────────────

// loadDerivativeManifest reads a target's index from disk once. A manifest written by an older
// version, or for a different tier geometry, is deliberately DISCARDED (its records are not
// trusted) so a changed filter can never be served as if it were current.
func loadDerivativeManifest(t placeholderDerivativeTarget) *PlaceholderDerivativeManifest {
	placeholderDerivManifestMu.Lock()
	defer placeholderDerivManifestMu.Unlock()
	if m, ok := placeholderDerivManifests[t.OutRoot]; ok && m != nil {
		return m
	}
	m := &PlaceholderDerivativeManifest{
		Version:    placeholderDerivativeManifestVersion,
		Root:       t.OutRoot,
		SlideWidth: PlaceholderDerivativeSlideWidth,
		ThumbWidth: PlaceholderDerivativeThumbWidth,
		Records:    make(map[string]*PlaceholderDerivativeRecord),
	}
	if data, err := os.ReadFile(t.ManifestPath); err == nil {
		var onDisk PlaceholderDerivativeManifest
		if jsonErr := json.Unmarshal(data, &onDisk); jsonErr == nil {
			if onDisk.Version == placeholderDerivativeManifestVersion &&
				onDisk.SlideWidth == PlaceholderDerivativeSlideWidth &&
				onDisk.ThumbWidth == PlaceholderDerivativeThumbWidth &&
				onDisk.Records != nil {
				m = &onDisk
			} else {
				log.Printf("[PlaceholderDerivatives] manifest %s is version %d / %dx%d px (want %d / %dx%d); re-deriving",
					t.ManifestPath, onDisk.Version, onDisk.SlideWidth, onDisk.ThumbWidth,
					placeholderDerivativeManifestVersion, PlaceholderDerivativeSlideWidth, PlaceholderDerivativeThumbWidth)
			}
		} else {
			log.Printf("[PlaceholderDerivatives] manifest %s is unreadable (%v); re-deriving", t.ManifestPath, jsonErr)
		}
	}
	placeholderDerivManifests[t.OutRoot] = m
	return m
}

// saveDerivativeManifest writes the index atomically (temp + rename), so an interrupted write can
// never leave a half-manifest that claims art exists when it does not.
func saveDerivativeManifest(t placeholderDerivativeTarget, m *PlaceholderDerivativeManifest) error {
	if m == nil {
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(t.ManifestPath), 0755); err != nil {
		return fmt.Errorf("could not create derivative root %s: %w", filepath.Dir(t.ManifestPath), err)
	}
	m.Version = placeholderDerivativeManifestVersion
	m.Root = t.OutRoot
	m.SlideWidth = PlaceholderDerivativeSlideWidth
	m.ThumbWidth = PlaceholderDerivativeThumbWidth
	m.GeneratedAt = time.Now()
	data, err := json.MarshalIndent(m, "", "  ")
	if err != nil {
		return fmt.Errorf("could not marshal derivative manifest: %w", err)
	}
	tmp := t.ManifestPath + ".tmp"
	if err := os.WriteFile(tmp, data, 0644); err != nil {
		return fmt.Errorf("could not write derivative manifest temp: %w", err)
	}
	if err := os.Rename(tmp, t.ManifestPath); err != nil {
		_ = os.Remove(tmp)
		return fmt.Errorf("could not commit derivative manifest: %w", err)
	}
	return nil
}

// PlaceholderDerivativeStatusForClient reports progress over the SERVED pack. It reads the
// in-memory index only: it never triggers work, so a status check is always cheap and honest.
func PlaceholderDerivativeStatusForClient() PlaceholderDerivativeStatus {
	skus := PlaceholderCatalogue()
	status := PlaceholderDerivativeStatus{
		Total:      len(skus),
		SlideWidth: PlaceholderDerivativeSlideWidth,
		ThumbWidth: PlaceholderDerivativeThumbWidth,
		Root:       placeholderDerivativeRoot,
		Rule: "The pack's originals are the source of truth; the server derives a light " +
			"slide (512 px) and thumb (128 px) rendition of every frame with a deterministic " +
			"integer box filter and records the sha256 of the bytes it actually wrote. A frame " +
			"whose art cannot be decoded is reported as failed and its original is used instead.",
	}
	placeholderDerivManifestMu.Lock()
	inProgress := placeholderDerivPassOn
	lastRun := placeholderDerivLastRun
	placeholderDerivManifestMu.Unlock()
	status.InProgress = inProgress
	status.GeneratedAt = lastRun
	t, err := placeholderDerivativeTargetForProduction()
	if err != nil {
		status.Pending = len(skus)
		return status
	}
	m := loadDerivativeManifest(t)
	placeholderDerivManifestMu.Lock()
	for _, s := range skus {
		rec := m.Records[s.SKU]
		switch {
		case rec == nil:
			status.Pending++
		case rec.Slide != nil && rec.Thumb != nil:
			status.Derived++
		case rec.Slide == nil && rec.Thumb == nil && rec.Failed != "":
			status.Failed++
		default:
			status.Pending++
		}
	}
	placeholderDerivManifestMu.Unlock()
	status.Ready = status.Total > 0 && status.Pending == 0 && status.Failed == 0
	return status
}

// PlaceholderDerivativeRecordFor returns one SKU's derived renditions as the server knows them.
// It is a pure read of the index — an underived frame answers false rather than being derived
// inside a request — and it returns a COPY, so a pass running concurrently can never mutate a
// record another goroutine is rendering.
func PlaceholderDerivativeRecordFor(sku string) (*PlaceholderDerivativeRecord, bool) {
	t, err := placeholderDerivativeTargetForProduction()
	if err != nil {
		return nil, false
	}
	key := strings.ToLower(strings.TrimSpace(sku))
	if key == "" {
		return nil, false
	}
	return derivativeRecordForTarget(t, key)
}

// derivativeRecordForTarget is the one read path for a record: it answers only when at least one
// rendition exists, and hands back a copy.
func derivativeRecordForTarget(t placeholderDerivativeTarget, sku string) (*PlaceholderDerivativeRecord, bool) {
	m := loadDerivativeManifest(t)
	placeholderDerivManifestMu.Lock()
	defer placeholderDerivManifestMu.Unlock()
	rec, ok := m.Records[sku]
	if !ok || rec == nil || (rec.Slide == nil && rec.Thumb == nil) {
		return nil, false
	}
	cp := *rec
	return &cp, true
}

// derivativeStoreRecord replaces one manifest entry under the lock.
func derivativeStoreRecord(m *PlaceholderDerivativeManifest, sku string, rec *PlaceholderDerivativeRecord) {
	if m == nil || rec == nil {
		return
	}
	placeholderDerivManifestMu.Lock()
	if m.Records == nil {
		m.Records = make(map[string]*PlaceholderDerivativeRecord)
	}
	m.Records[sku] = rec
	placeholderDerivManifestMu.Unlock()
}

// ── The pass ─────────────────────────────────────────────────────────────────────────────────

// PlaceholderDerivativePassResult reports what one pass did, including what it could not do.
type PlaceholderDerivativePassResult struct {
	Total   int      `json:"total"`
	Derived int      `json:"derived"`
	Reused  int      `json:"reused"`
	Failed  int      `json:"failed"`
	Errors  []string `json:"errors,omitempty"`
}

// placeholderDerivativePriority returns the frames to derive FIRST: the ones the app's own
// slideshows display, taken from the slide declaration itself so the list cannot drift away from
// the slides. The boot screen therefore gets light art before the rest of the pack is touched.
func placeholderDerivativePriority() []string {
	out := make([]string, 0, len(slideSlotDefs)+len(placeholderStarterSKUs))
	seen := make(map[string]bool)
	for _, d := range slideSlotDefs {
		if !seen[d.DefaultSKU] {
			seen[d.DefaultSKU] = true
			out = append(out, d.DefaultSKU)
		}
	}
	for _, s := range placeholderStarterSKUs {
		if !seen[s] {
			seen[s] = true
			out = append(out, s)
		}
	}
	return out
}

// orderSkusForDerivation puts the priority frames first and keeps catalogue order for the rest, so
// a pass is deterministic and always serves the visible surfaces first.
func orderSkusForDerivation(skus []PlaceholderSku, priority []string) []PlaceholderSku {
	want := make(map[string]int, len(priority))
	for i, sku := range priority {
		want[strings.ToLower(strings.TrimSpace(sku))] = i + 1
	}
	out := make([]PlaceholderSku, 0, len(skus))
	for rank := 1; rank <= len(priority); rank++ {
		for _, s := range skus {
			if want[s.SKU] == rank {
				out = append(out, s)
			}
		}
	}
	for _, s := range skus {
		if want[s.SKU] == 0 {
			out = append(out, s)
		}
	}
	return out
}

// derivativeFilesPresent reports whether every recorded rendition is actually on disk. A record
// whose file was deleted (or hand-cleaned) is NOT reusable: the manifest is an index, not a
// promise, so the FILE is what decides.
func derivativeFilesPresent(t placeholderDerivativeTarget, rec *PlaceholderDerivativeRecord) bool {
	check := func(d *PlaceholderDerivative) bool {
		if d == nil || d.Passthrough {
			return true
		}
		p, ok := t.pathForURI(d.URI)
		if !ok {
			return false
		}
		info, err := os.Stat(p)
		return err == nil && info.Size() > 0
	}
	return check(rec.Slide) && check(rec.Thumb)
}

// ensureDerivativeForSKU derives one frame's two tiers unless the recorded renditions are still
// valid for the source's CURRENT hash. It returns how many renditions it wrote (0 when reused).
func ensureDerivativeForSKU(t placeholderDerivativeTarget, m *PlaceholderDerivativeManifest, s PlaceholderSku) (written int, reused bool, err error) {
	srcHash, hashErr := placeholderSkuHash(s)
	if hashErr != nil {
		return 0, false, hashErr
	}
	placeholderDerivManifestMu.Lock()
	prev := m.Records[s.SKU]
	placeholderDerivManifestMu.Unlock()
	if prev != nil && prev.SourceHashHex == srcHash && prev.Failed == "" && derivativeFilesPresent(t, prev) {
		return 0, true, nil
	}
	slide, slideErr := derivePNGToWidth(
		s.path, t.outPathFor(s, PlaceholderDerivativeSlideTier), t.uriFor(s, PlaceholderDerivativeSlideTier),
		PlaceholderDerivativeSlideTier, PlaceholderDerivativeSlideWidth, s.URI)
	thumb, thumbErr := derivePNGToWidth(
		s.path, t.outPathFor(s, PlaceholderDerivativeThumbTier), t.uriFor(s, PlaceholderDerivativeThumbTier),
		PlaceholderDerivativeThumbTier, PlaceholderDerivativeThumbWidth, s.URI)
	rec := &PlaceholderDerivativeRecord{
		SKU: s.SKU, SourceURI: s.URI, SourceHashHex: srcHash,
		SourceBytes: s.Bytes, SourceWidth: s.Width, SourceHeight: s.Height,
		Slide: slide, Thumb: thumb, UpdatedAt: time.Now(),
	}
	written = 0
	if slide != nil {
		written++
	}
	if thumb != nil {
		written++
	}
	switch {
	case slideErr != nil && thumbErr != nil:
		rec.Failed = "no rendition could be derived: " + slideErr.Error()
	case slideErr != nil:
		rec.Failed = "slide rendition refused: " + slideErr.Error()
	case thumbErr != nil:
		rec.Failed = "thumb rendition refused: " + thumbErr.Error()
	}
	derivativeStoreRecord(m, s.SKU, rec)
	if rec.Failed != "" {
		return written, false, fmt.Errorf("%s: %s", s.SKU, rec.Failed)
	}
	return written, false, nil
}

// runPlaceholderDerivativePass derives every frame it cannot honestly reuse. It is the ONLY
// writer: one pass at a time, the index updated as it goes (so a reader watching status sees real
// progress), and the manifest committed once at the end.
func runPlaceholderDerivativePass(t placeholderDerivativeTarget, skus []PlaceholderSku, priority []string) *PlaceholderDerivativePassResult {
	placeholderDerivPassMu.Lock()
	defer placeholderDerivPassMu.Unlock()
	res := &PlaceholderDerivativePassResult{Total: len(skus), Errors: make([]string, 0)}
	placeholderDerivManifestMu.Lock()
	placeholderDerivPassOn = true
	placeholderDerivManifestMu.Unlock()
	defer func() {
		placeholderDerivManifestMu.Lock()
		placeholderDerivPassOn = false
		placeholderDerivLastRun = time.Now()
		placeholderDerivManifestMu.Unlock()
	}()
	if err := os.MkdirAll(t.OutRoot, 0755); err != nil {
		res.Failed = len(skus)
		res.Errors = append(res.Errors, fmt.Sprintf("derivative root %s is not writable: %v", t.OutRoot, err))
		return res
	}
	m := loadDerivativeManifest(t)
	for _, s := range orderSkusForDerivation(skus, priority) {
		written, reused, err := ensureDerivativeForSKU(t, m, s)
		switch {
		case err != nil:
			res.Failed++
			if len(res.Errors) < 20 {
				res.Errors = append(res.Errors, err.Error())
			}
		case reused:
			res.Reused++
		default:
			res.Derived += written
		}
	}
	if err := saveDerivativeManifest(t, m); err != nil {
		res.Errors = append(res.Errors, err.Error())
	}
	return res
}

// EnsurePlaceholderDerivatives runs one pass over the SERVED pack. It is safe to call repeatedly:
// a pass whose index is already valid reuses every record and writes nothing.
func EnsurePlaceholderDerivatives() *PlaceholderDerivativePassResult {
	skus := PlaceholderCatalogue()
	t, err := placeholderDerivativeTargetForProduction()
	if err != nil {
		return &PlaceholderDerivativePassResult{
			Total: len(skus), Failed: len(skus), Errors: []string{err.Error()},
		}
	}
	return runPlaceholderDerivativePass(t, skus, placeholderDerivativePriority())
}

// StartPlaceholderDerivativeWarmup derives the light art in the BACKGROUND, once per process.
//
// It is deliberately not awaited by anything: boot must never wait on 117 PNG decodes. The
// slideshow frames are derived first, so the surfaces a player actually sees stop being heavy
// within seconds, and every reader falls back to the original (reported as pending) until then.
func StartPlaceholderDerivativeWarmup() {
	placeholderDerivWarmOnce.Do(func() {
		go func() {
			started := time.Now()
			res := EnsurePlaceholderDerivatives()
			if res == nil {
				return
			}
			log.Printf("[PlaceholderDerivatives] pass finished in %s: %d renditions written, %d frames reused, %d failed",
				time.Since(started).Round(time.Millisecond), res.Derived, res.Reused, res.Failed)
			for _, e := range res.Errors {
				log.Printf("[PlaceholderDerivatives] %s", e)
			}
		}()
	})
}

// ── Served view ──────────────────────────────────────────────────────────────────────────────

// PlaceholderSkuView is a catalogue SKU plus its derived renditions, assembled at SERVE time. The
// cached catalogue holds ORIGINALS only, so a rendition that appears later is picked up on the next
// read without invalidating the pack scan (the file list must stay the SKU list).
type PlaceholderSkuView struct {
	PlaceholderSku
	// Derivatives carries the derived renditions (real uris, byte sizes and hashes) when they
	// exist, and is absent while a frame is still pending — the client then uses `uri`.
	Derivatives *PlaceholderDerivativeRecord `json:"derivatives,omitempty"`
	// DerivativeNote states, in words, why a frame has no light rendition yet.
	DerivativeNote string `json:"derivative_note,omitempty"`
}

// PlaceholderCatalogueViews returns the whole pack with each frame's derived renditions attached,
// so a client can fetch the light art in preference to the multi-megabyte original.
func PlaceholderCatalogueViews() []PlaceholderSkuView {
	skus := PlaceholderCatalogue()
	out := make([]PlaceholderSkuView, 0, len(skus))
	for _, s := range skus {
		v := PlaceholderSkuView{PlaceholderSku: s}
		if rec, ok := PlaceholderDerivativeRecordFor(s.SKU); ok {
			v.Derivatives = rec
			if rec.Failed != "" {
				v.DerivativeNote = rec.Failed
			}
		} else {
			v.DerivativeNote = "no light rendition yet: the server is still deriving the pack, so the original art is the one to fetch"
		}
		out = append(out, v)
	}
	return out
}


// PlaceholderDerivativeURIForSKU prefers a derived rendition of a frame, falling back to the
// original. The boolean reports whether the URI is a DERIVED one, so a caller can say so instead
// of implying the light art is the shipped art.
func PlaceholderDerivativeURIForSKU(sku, tier string) (string, bool) {
	rec, ok := PlaceholderDerivativeRecordFor(sku)
	if !ok {
		return "", false
	}
	s, have := placeholderSku(sku)
	switch tier {
	case PlaceholderDerivativeSlideTier:
		if rec.Slide != nil {
			if !rec.Slide.Passthrough {
				return rec.Slide.URI, true
			}
			if have {
				return s.URI, false
			}
			return rec.Slide.URI, false
		}
	case PlaceholderDerivativeThumbTier:
		if rec.Thumb != nil {
			if !rec.Thumb.Passthrough {
				return rec.Thumb.URI, true
			}
			if have {
				return s.URI, false
			}
			return rec.Thumb.URI, false
		}
	default:
		return "", false
	}
	if have {
		return s.URI, false
	}
	return "", false
}

// ── The filter (deterministic, integer, dependency-free) ─────────────────────────────────────

// integerBoxDownscale returns a box-filtered copy of src whose width is exactly maxW, or nil when
// no downscale is needed (src is already at or below maxW — then the source IS the derivative).
//
// Every output pixel is the AVERAGE of the source pixels it covers, accumulated in uint64. The
// colour sum is alpha-weighted (premultiplied) and then divided by the accumulated alpha, which is
// what keeps a transparent frame from developing dark halos — the standard correct way to resample
// an image with alpha, done with integer arithmetic only:
//
//	outA = Σa / n            (the average coverage)
//	outC = Σ(c·a) / Σa       (the coverage-weighted colour, un-premultiplied)
//
// No float appears anywhere, so the same input produces the identical output on every platform.
func integerBoxDownscale(src image.Image, maxW uint64) image.Image {
	if src == nil || maxW == 0 {
		return nil
	}
	b := src.Bounds()
	sw, sh := uint64(b.Dx()), uint64(b.Dy())
	if sw == 0 || sh == 0 || sw <= maxW {
		return nil
	}
	dw := maxW
	dh := sh * dw / sw
	if dh == 0 {
		dh = 1
	}
	dst := image.NewRGBA(image.Rect(0, 0, int(dw), int(dh)))
	for y := uint64(0); y < dh; y++ {
		// Integer box bounds: [y·sh/dh, (y+1)·sh/dh). Guaranteed at least one source row tall.
		y0 := y * sh / dh
		y1 := (y + 1) * sh / dh
		if y1 <= y0 {
			y1 = y0 + 1
		}
		for x := uint64(0); x < dw; x++ {
			x0 := x * sw / dw
			x1 := (x + 1) * sw / dw
			if x1 <= x0 {
				x1 = x0 + 1
			}
			var sumA, sumR, sumG, sumB, n uint64
			for sy := y0; sy < y1; sy++ {
				for sx := x0; sx < x1; sx++ {
					r, g, bl, a := src.At(b.Min.X+int(sx), b.Min.Y+int(sy)).RGBA()
					aa := uint64(a)
					sumA += aa
					sumR += uint64(r) * aa
					sumG += uint64(g) * aa
					sumB += uint64(bl) * aa
					n++
				}
			}
			if n == 0 {
				continue
			}
			outA := sumA / n
			var outR, outG, outB uint64
			if sumA > 0 {
				outR = sumR / sumA
				outG = sumG / sumA
				outB = sumB / sumA
			}
			// image.RGBA is premultiplied: the accumulated values already are, so they are
			// narrowed from 16-bit to 8-bit and stored directly.
			i := dst.PixOffset(int(x), int(y))
			dst.Pix[i+0] = uint8(outR >> 8)
			dst.Pix[i+1] = uint8(outG >> 8)
			dst.Pix[i+2] = uint8(outB >> 8)
			dst.Pix[i+3] = uint8(outA >> 8)
		}
	}
	return dst
}

// servedURIPathFor turns a path under the served Public/ tree into the same-origin URI a client
// fetches (Public/Assets/x.png → /Assets/x.png). It refuses to invent a URL for anything outside
// the served tree, so a misplaced derivation is an error rather than a broken image.
func servedURIPathFor(p string) (string, error) {
	slash := filepath.ToSlash(p)
	clean := strings.TrimPrefix(strings.TrimPrefix(slash, "./"), "/")
	const served = "Public/"
	if !strings.HasPrefix(clean, served) {
		return "", fmt.Errorf("path %q is not inside the served %s tree, so it has no URI", p, served)
	}
	return "/" + strings.TrimPrefix(clean, served), nil
}

// placeholderDerivativeTarget is the read/write geometry of a derivative pass. It exists so the
// pass can be pointed at a temporary root by a test (and at the real served pack by the server)
// with no hidden global: every path and URI it uses comes from here.
type placeholderDerivativeTarget struct {
	ArtRoot      string // where the ORIGINALS are read from
	OutRoot      string // where renditions are written
	URIPrefix    string // the same-origin prefix OutRoot is served at (trailing slash)
	ManifestPath string
}

// placeholderDerivativeTargetForProduction is the one declaration of where the shipped pack's
// renditions live. It validates that the out root really is inside the served tree, so a mistake
// here is a startup error rather than a grid of broken images.
func placeholderDerivativeTargetForProduction() (placeholderDerivativeTarget, error) {
	uriRoot, err := servedURIPathFor(placeholderDerivativeRoot)
	if err != nil {
		return placeholderDerivativeTarget{}, err
	}
	return placeholderDerivativeTarget{
		ArtRoot:      placeholderArtRoot,
		OutRoot:      placeholderDerivativeRoot,
		URIPrefix:    uriRoot + "/",
		ManifestPath: filepath.Join(placeholderDerivativeRoot, placeholderDerivativeManifestFile),
	}, nil
}

// pathForURI maps a recorded derivative URI back to the file it should be, or false when the URI
// does not belong to this target (so a record from another root is never mistaken for this one).
func (t placeholderDerivativeTarget) pathForURI(uri string) (string, bool) {
	if uri == "" || !strings.HasPrefix(uri, t.URIPrefix) {
		return "", false
	}
	rel := strings.TrimPrefix(uri, t.URIPrefix)
	if rel == "" || strings.Contains(rel, "..") {
		return "", false
	}
	return filepath.Join(t.OutRoot, filepath.FromSlash(rel)), true
}

// outPathFor is where one tier's rendition of a frame is written: the character directory is
// preserved and the tier is a file suffix, so a generated frame is greppable and obviously
// derived from its original.
func (t placeholderDerivativeTarget) outPathFor(s PlaceholderSku, tier string) string {
	return filepath.Join(t.OutRoot, s.Character, fmt.Sprintf("%s-%03d-%s.png", s.Character, s.Frame, tier))
}

// uriFor is the served address of that rendition.
func (t placeholderDerivativeTarget) uriFor(s PlaceholderSku, tier string) string {
	return t.URIPrefix + s.Character + "/" + fmt.Sprintf("%s-%03d-%s.png", s.Character, s.Frame, tier)
}

// derivePNGToWidth is the pure, path-driven derivation used by the pass and by tests: it decodes
// srcPath, box-downscales it to maxW, encodes it to dstPath, and returns the MEASURED facts of
// what was written (byte size, pixel size and the sha256 of the encoded bytes).
//
// A source already at or below maxW yields a Passthrough derivative that names the SOURCE file —
// no duplicate file is written, and no art is invented.
func derivePNGToWidth(srcPath, dstPath, outURI, tier string, maxW uint64, sourceURI string) (*PlaceholderDerivative, error) {
	f, err := os.Open(srcPath)
	if err != nil {
		return nil, fmt.Errorf("could not open source art: %w", err)
	}
	src, err := png.Decode(f)
	_ = f.Close()
	if err != nil {
		return nil, fmt.Errorf("source art could not be decoded as a PNG: %w", err)
	}
	b := src.Bounds()
	sw, sh := uint64(b.Dx()), uint64(b.Dy())
	if sw == 0 || sh == 0 {
		return nil, fmt.Errorf("source art declares no pixel dimensions")
	}
	if sw <= maxW {
		sum, hashErr := hashFileSHA256(srcPath)
		if hashErr != nil {
			return nil, hashErr
		}
		return &PlaceholderDerivative{
			Tier: tier, URI: sourceURI, Bytes: uint64(fileSize(srcPath)), Width: sw, Height: sh,
			HashHex: sum, MimeType: "image/png", Passthrough: true, GeneratedAt: time.Now(),
		}, nil
	}
	small := integerBoxDownscale(src, maxW)
	if small == nil {
		return nil, fmt.Errorf("the box filter produced no image for %dx%d at %d px wide", sw, sh, maxW)
	}
	if err := os.MkdirAll(filepath.Dir(dstPath), 0755); err != nil {
		return nil, fmt.Errorf("could not create derivative directory: %w", err)
	}
	tmp := dstPath + ".tmp"
	out, err := os.Create(tmp)
	if err != nil {
		return nil, fmt.Errorf("could not create derivative file: %w", err)
	}
	enc := png.Encoder{CompressionLevel: png.DefaultCompression}
	encErr := enc.Encode(out, small)
	if closeErr := out.Close(); encErr == nil {
		encErr = closeErr
	}
	if encErr != nil {
		_ = os.Remove(tmp)
		return nil, fmt.Errorf("could not encode derivative: %w", encErr)
	}
	if err := os.Rename(tmp, dstPath); err != nil {
		_ = os.Remove(tmp)
		return nil, fmt.Errorf("could not commit derivative: %w", err)
	}
	sum, err := hashFileSHA256(dstPath)
	if err != nil {
		return nil, err
	}
	ob := small.Bounds()
	return &PlaceholderDerivative{
		Tier: tier, URI: outURI, Bytes: uint64(fileSize(dstPath)),
		Width: uint64(ob.Dx()), Height: uint64(ob.Dy()),
		HashHex: sum, MimeType: "image/png", GeneratedAt: time.Now(),
	}, nil
}

// hashFileSHA256 is the real sha256 of a file on disk — the same digest a client can recompute
// after fetching the art.
func hashFileSHA256(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", fmt.Errorf("could not read %s: %w", path, err)
	}
	defer f.Close()
	h := sha256.New()
	if _, err := io.Copy(h, f); err != nil {
		return "", fmt.Errorf("could not hash %s: %w", path, err)
	}
	return hex.EncodeToString(h.Sum(nil)), nil
}

// fileSize reports a file's size (0 when it cannot be read — the caller reports that separately).
func fileSize(path string) int64 {
	info, err := os.Stat(path)
	if err != nil {
		return 0
	}
	return info.Size()
}
